### ISSUE TITLE
Missing MSVCP140D.dll

### ISSUE THREAD

**Issue by Jerther** [AbyssEngine/AbyssEngineOld#119]
**Describe the bug**
---------------------------
AbyssEngine.exe - System Error
---------------------------
The code execution cannot proceed because MSVCP140D.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------

Other similar errors about missing dlls follow this one.

**To Reproduce**
Run AbyssEngine.exe

**Expected behavior**
The game starts

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 98.0.4758.102

**Additional context**
- I couldn't find the runtime for the D variant
- I also couldn't install VS2015 with the web installer, at which point I gave up.

**Comment by cookta2012** [comment]
What version of Windows 10? Have you insured that your windows is not corrupt by running

SFC /scannow

In an elevated command prompt

**Comment by Jerther** [comment]
Version	10.0.19042 Build 19042
sfc /scannow did not find any problem.

Thing is, there IS a MSVCP140.dll file in the bin folder, just NOT the D variant MSVCP140D.dll.

I tried to rename the filed to their D counterpart and now ucrtbased.dll is missing, which is again a D variant of ucrtbase.dll that comes, again, with Visual Studio 2015 or something, and all the web installers are outdated and won't work.

So I finally found a working Visual Studio Build Tools package [here, more precisely in the comments](https://stackoverflow.com/a/54136652/2498426). In "Desktop development with C++", I selected "MSVC v140 - VS 2015 C++ build tools" in addition to what was already selected. This took a while to download (2.48GB) and to install (10GB installed), but finally I got past the missing DLLs messages.

If I had to take a guess, I believe the latest release was built in **debug** mode, while the dev build process copied the **release** DLLs in the output folder, and also missed some other required ones.

I now have [this issue](https://github.com/AbyssEngine/OpenDiablo2/issues/38).

**Comment by cookta2012** [comment]
Okay and I will let Essial know.

**Comment by cookta2012** [comment]
I may have to spin up a Windows VM to check this out thank you for
reporting it.

**Comment by essial** [comment]
Please join us on discord if you'd like help troubleshooting your specific. My first thought is you are missing the latest Microsoft C++ SDK libraries. You are bulding in debug mode and it is looking for the DEV (D) version of the runtime and can't find it.
