### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by nunotexbsd** [AbyssEngine/AbyssEngineOld#123]
Hello,

Looking for install instruction for porting to Unix FreeBSD:

run, build, lib dependencies.

Thanks

**Comment by essial** [comment]
Feel free to join the discord channel if you want direct help with troubleshooting the build. The simplest way is to use VCPKG to pull down the dependencies though.

**Comment by nunotexbsd** [comment]
Hello,

vcpkg has not yet been ported to FreeBSD but it seems that someone fixed building, issue [21229](https://github.com/microsoft/vcpkg/issues/21229) what is good news.

Soon I will try it.

Thanks

**Comment by DarthGandalf** [comment]
vcpkg.json in the repo root can be used to get an idea of what deps you need even if you can't use vcpkg tool directly. Probably FreeBSD has most of the deps packaged

**Comment by nunotexbsd** [comment]
Hi @DarthGandalf,

Thanks for info.
I think I have what I need to start porting AbyssEngine to FreeBSD.

Cheers

**Comment by essial** [comment]
Is this still an issue that needs to be tracked, or can we close it?

**Comment by nunotexbsd** [comment]
Sorry, forgot to close.

Thanks
