### ISSUE TITLE
abyss_test linking: undefined symbol

### ISSUE THREAD

**Issue by M0Rf30** [AbyssEngine/AbyssEngineOld#129]
**Describe the bug**
Reaching the end of build process this message pop out

```
[100%] Linking CXX executable abyss_test
mold: error: undefined symbol: absl::lts_20220623::container_internal::ConvertDeletedToEmptyAndFullToDeleted(absl::lts_20220623::container_internal::ctrl_t*, unsigned long)
>>> referenced by inifile.cpp
```
Would be great to skip the tests with an appropriate flag using cmake, for example launching:
```
cmake ../abyss-sources \
    -DBUILD_TESTING=off \
``` 
Thanks for your amazing efforts, I follow this project since the early days.

**Additional note:** 
mold (referenced in the log) is a drop-in replacement for gold (the GNU linker). same issue also with gold anyway

**Workaround**
For now I'm using this workaround
```
# temporary workaround to disable tests
  pacman -S gtest
  rm -rf tests/*
  touch tests/CMakeLists.txt
```

**Comment by essial** [comment]
Thanks for the report! We will look into this issue and get back as soon as we can.
